/**
 * NIT KKR 2025-26 Crawler Configuration
 */

export const CRAWLER_CONFIG = {
  // Official Base URL (Configurable via environment variable)
  NIT_KKR_BASE_URL: process.env.NIT_KKR_BASE_URL || 'https://nitkkr.ac.in/',

  // Target Academic Year Scope
  TARGET_ACADEMIC_YEAR: process.env.TARGET_ACADEMIC_YEAR || '2025-26',
  ACADEMIC_YEAR_BOUNDARIES: {
    startDate: new Date('2025-07-01T00:00:00.000Z'),
    endDate: new Date('2026-06-30T23:59:59.999Z'),
  },

  // Polite Crawling Defaults
  DEFAULT_REQUEST_DELAY_MS: 1000,
  MIN_REQUEST_DELAY_MS: 200,
  MAX_REQUEST_DELAY_MS: 10000,
  DEFAULT_MAX_PAGES_PER_RUN: 50,
  MAX_ALLOWED_PAGES_PER_RUN: 1000,
  REQUEST_TIMEOUT_MS: 15000,
  MAX_RETRIES: 2,
  INITIAL_RETRY_DELAY_MS: 1500,

  // HTML Content Ingestion
  INGEST_HTML_CONTENT: true,
  MIN_HTML_TEXT_LENGTH: 150, // Minimum characters required to index an HTML page

  // Resource Size Limits (Protection against oversized responses)
  MAX_HTML_SIZE_BYTES: 5 * 1024 * 1024, // 5 MB
  MAX_PDF_SIZE_BYTES: 50 * 1024 * 1024,  // 50 MB
  MAX_PDF_PAGES: parseInt(process.env.MAX_PDF_PAGES || '200', 10), // Maximum pages per individual PDF document

  // Allowed Content Types
  ALLOWED_CONTENT_TYPES: ['text/html', 'application/pdf', 'application/x-pdf'],

  // HTTP User-Agent Header
  USER_AGENT:
    'AskCampusAi-Bot/1.0 (+https://nitkkr.ac.in; academic research & official student assistance)',

  // Allowed Protocols
  ALLOWED_PROTOCOLS: ['http:', 'https:'],

  // Collection Date Scope (2025-01-01 through current date)
  COLLECTION_START_DATE: new Date('2025-01-01T00:00:00.000Z'),

  // Expanded Official NIT KKR Crawlable HTML Paths
  EXPANDED_ALLOWED_PATH_PREFIXES: [
    '/academic-notifications/',
    '/exam-notifications/',
    '/academic-calender/',
    '/notification-notices/',
    '/category/announcements/',
    '/category/notifications/',
    '/notifications-2/',
    '/resultnotifications/',
    '/scholarship-notifications/',
    '/b-tech/',
    '/dasa-mea-iccr-iis/',
    '/notification-archived/',
    '/training-and-placement/',
    '/placement-policies/',
    '/syllabus/',
    '/scheme-and-syllabi/',
    '/hostels/',
    '/rules-and-regulations/',
    '/events/',
  ],

  // Allowed PDF Destination Prefix (Only downloaded when linked from approved HTML pages)
  ALLOWED_PDF_PREFIX: '/wp-content/uploads/',

  // Initial Seed Sources for NIT Kurukshetra
  DEFAULT_SOURCES: [
    {
      name: 'NIT KKR Academic Notifications',
      baseUrl: 'https://nitkkr.ac.in/academic-notifications/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/academic-notifications/'],
      priority: 'high',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 25,
      requestDelayMs: 1000,
      defaultCategory: 'academics',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR Examination Notifications',
      baseUrl: 'https://nitkkr.ac.in/exam-notifications/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/exam-notifications/'],
      priority: 'high',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 25,
      requestDelayMs: 1000,
      defaultCategory: 'examinations',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR Academic Calendar',
      baseUrl: 'https://nitkkr.ac.in/academic-calender/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/academic-calender/'],
      priority: 'high',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 15,
      requestDelayMs: 1000,
      defaultCategory: 'academics',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR General Notices & Notifications',
      baseUrl: 'https://nitkkr.ac.in/notification-notices/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/notification-notices/'],
      priority: 'high',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 25,
      requestDelayMs: 1000,
      defaultCategory: 'notices',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR Scholarship Notifications',
      baseUrl: 'https://nitkkr.ac.in/scholarship-notifications/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/scholarship-notifications/'],
      priority: 'high',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 25,
      requestDelayMs: 1000,
      defaultCategory: 'scholarships',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR Result Notifications',
      baseUrl: 'https://nitkkr.ac.in/resultnotifications/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/resultnotifications/'],
      priority: 'high',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 25,
      requestDelayMs: 1000,
      defaultCategory: 'examinations',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR Category Announcements',
      baseUrl: 'https://nitkkr.ac.in/category/announcements/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/category/announcements/'],
      priority: 'medium',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 20,
      requestDelayMs: 1000,
      defaultCategory: 'notices',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR Category Notifications',
      baseUrl: 'https://nitkkr.ac.in/category/notifications/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/category/notifications/'],
      priority: 'medium',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 20,
      requestDelayMs: 1000,
      defaultCategory: 'notices',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR Notifications 2',
      baseUrl: 'https://nitkkr.ac.in/notifications-2/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/notifications-2/'],
      priority: 'medium',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 20,
      requestDelayMs: 1000,
      defaultCategory: 'notices',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR B.Tech Portal',
      baseUrl: 'https://nitkkr.ac.in/b-tech/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/b-tech/'],
      priority: 'medium',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 15,
      requestDelayMs: 1000,
      defaultCategory: 'academics',
      defaultDepartment: 'General',
    },
    {
      name: 'NIT KKR DASA / MEA / ICCR International Admissions',
      baseUrl: 'https://nitkkr.ac.in/dasa-mea-iccr-iis/',
      allowedDomains: ['nitkkr.ac.in'],
      allowedPathPrefixes: ['/dasa-mea-iccr-iis/'],
      priority: 'medium',
      studentKnowledgeBaseOnly: true,
      sourceAuthority: 'official',
      academicYear: '2025-26',
      enabled: true,
      crawlFrequency: 'manual',
      maxPagesPerRun: 15,
      requestDelayMs: 1000,
      defaultCategory: 'admissions',
      defaultDepartment: 'General',
    },
  ],
};

export default CRAWLER_CONFIG;
